name: ItemMail
version: 0.1
main: com.imyvm.ItemMail.ItemMail
depend: [Vault, Rewards]
api-version: 1.13

commands:
  itemmail:
    description: All commands
    aliases: [itemmail, imail]

permissions:
  ItemMail.player.*:
    children:
      ItemMail.send.self: true
      ItemMail.get: true
      ItemMail.send.total: true
      ItemMail.send.others: true
      ItemMail.send.confirm: true
      ItemMial.open: true
  ItemMail.admin.*:
    children:
      ItemMail.open.others: true
      ItemMail.create: true